[package]
name = "crypto_utils"
version = "1.0.0"
edition = "2024"

[dependencies]
aes-gcm.workspace = true
aes.workspace = true
rand.workspace = true
base64.workspace = true
once_cell.workspace = true
dotenvy.workspace = true
